-- 시퀀스
DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ NOCACHE;

-- 테이블
DROP TABLE BOARD;
CREATE TABLE BOARD (
	BOARD_NO 		NUMBER NOT NULL,
	TITLE 			VARCHAR2(1000 BYTE) NOT NULL,
	CONTENT			CLOB,
	MODIFIED_DATE 	DATE,
	CREATED_DATE 	DATE NOT NULL,  
	CONSTRAINT PK_BOARD PRIMARY KEY(BOARD_NO)
);

-- 행(ROW)
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, '[공지]월요일알림', 'DBCP는 DataBase Connection Pool을 의미한다.', NULL, SYSDATE); 
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, '[공지]비상 월요일알림', '월요일 1교시 부터 졸린 나, 정상인가요?', NULL, SYSDATE); 
COMMIT

